[package]
name = "descent-ground"
version = "0.4.5"
edition = "2021"

[dependencies]
serialport = { version = "4.10", default-features = false }
tiny_http = "0.12"
tungstenite = "0.30"
include_dir = "0.7"
webbrowser = "1.2"
espflash = { version = "4.6", default-features = false, features = ["serialport"] }
humantime = "2.1"

[profile.release]
opt-level = "z"
lto = true
strip = true
